#!/usr/bin/env node
"use strict";

// Turns a validated milestone handoff (devrel/inbox/*.yml) into deterministic
// draft Markdown: a development log, a LinkedIn draft, and release notes.
//
// This script only reorganizes facts that are already present in the
// handoff and devrel/config.yml. It never invents metrics, technical
// behavior, or outcomes, and it never publishes anything - it writes
// Markdown files to disk for a human to review and edit before posting.
//
// Running it twice on the same handoff produces byte-identical output
// (no timestamps, no randomness) - that's the "deterministic" contract.

const fs = require("node:fs");
const path = require("node:path");
const YAML = require("yaml");
const { loadHandoff, validateHandoff, REPO_ROOT } = require("./validate-handoff.js");

function loadConfig() {
  const configPath = path.join(REPO_ROOT, "devrel", "config.yml");
  const raw = fs.readFileSync(configPath, "utf8");
  return YAML.parse(raw);
}

function bulletList(items, fallback) {
  if (!Array.isArray(items) || items.length === 0) {
    return fallback;
  }
  return items.map((item) => `- ${item}`).join("\n");
}

function pathList(items, fallback) {
  if (!Array.isArray(items) || items.length === 0) {
    return fallback;
  }
  return items.map((item) => `- \`${item}\``).join("\n");
}

function generatedFromNotice(handoffPath) {
  const relativeHandoffPath = path.relative(REPO_ROOT, handoffPath);
  return (
    `<!-- Generated by scripts/devrel/generate-drafts.js from ${relativeHandoffPath}. ` +
    "Human review required before publishing. Do not publish automatically. -->"
  );
}

function generateDevelopmentLog(handoff, config, handoffPath) {
  const testRows = handoff.tests
    .map((entry) => `| \`${entry.command}\` | ${entry.result} |`)
    .join("\n");

  return `# ${handoff.title}

${generatedFromNotice(handoffPath)}

**Project:** ${config.project_name}
**Milestone:** \`${handoff.milestone_id}\`
**Date:** ${handoff.date}
**Status:** ${handoff.status}

## Summary

${handoff.summary}

## Implemented Features

${bulletList(handoff.implemented_features, "- None recorded.")}

## Visible User-Facing Changes

${bulletList(handoff.visible_user_facing_changes, "- None - this milestone is internal only.")}

## Commands Added

${bulletList(handoff.commands_added, "- None.")}

## Tests

| Command | Result |
| --- | --- |
${testRows}

## Approved Technical Decisions

${bulletList(handoff.approved_technical_decisions, "- None recorded.")}

## Known Limitations

${bulletList(handoff.known_limitations, "- None recorded.")}

## Commits / PRs

${bulletList(handoff.commits_or_prs, "- Not yet committed or merged.")}

## Media

Screenshots:
${pathList(handoff.screenshots, "- None yet.")}

Videos:
${pathList(handoff.videos, "- None yet.")}
`;
}

function generateLinkedIn(handoff, config, handoffPath) {
  const claimsToAvoid = bulletList(config.claims_to_avoid, "- (none configured)");

  return `${generatedFromNotice(handoffPath)}
<!-- Reviewer checklist before posting - remove this comment block first:
${claimsToAvoid}
-->

**${config.project_name}** - ${config.tagline}

${handoff.summary}

What shipped in "${handoff.title}":

${bulletList(handoff.implemented_features, "- (nothing recorded)")}

What you'd notice if you were using it:

${bulletList(handoff.visible_user_facing_changes, "- Nothing user-visible in this milestone - it's internal.")}

What's still missing / known limitations:

${bulletList(handoff.known_limitations, "- Nothing noted.")}

Repo: ${config.repository_url}
${config.portfolio_url}
`;
}

function generateReleaseNotes(handoff, config, handoffPath) {
  const added = [...handoff.implemented_features, ...handoff.commands_added];
  const testSummary = handoff.tests.map((entry) => `\`${entry.command}\` -> ${entry.result}`).join("; ");

  return `# ${config.project_name} - ${handoff.title}

${generatedFromNotice(handoffPath)}

**Milestone:** \`${handoff.milestone_id}\`
**Date:** ${handoff.date}
**Status:** ${handoff.status}

## Added

${bulletList(added, "- Nothing recorded.")}

## Changed

${bulletList(handoff.visible_user_facing_changes, "- No user-facing changes noted.")}

## Known Limitations

${bulletList(handoff.known_limitations, "- None recorded.")}

## Tests

${testSummary || "No tests recorded."}

## Links

${bulletList(handoff.commits_or_prs, "- Not yet committed or merged.")}
`;
}

function writeDraft(outputDir, milestoneId, contents) {
  fs.mkdirSync(outputDir, { recursive: true });
  const outputPath = path.join(outputDir, `${milestoneId}.md`);
  fs.writeFileSync(outputPath, contents, "utf8");
  return outputPath;
}

function main() {
  const handoffArg = process.argv[2];

  if (!handoffArg) {
    process.stderr.write("Usage: node scripts/devrel/generate-drafts.js <path-to-handoff.yml>\n");
    process.exitCode = 1;
    return;
  }

  let handoff;
  let handoffPath;

  try {
    ({ handoff, handoffPath } = loadHandoff(handoffArg));
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
    return;
  }

  const errors = validateHandoff(handoff);

  if (errors.length > 0) {
    process.stderr.write(
      `${handoffPath} failed validation - refusing to generate drafts from an invalid handoff:\n`
    );
    for (const error of errors) {
      process.stderr.write(`  - ${error}\n`);
    }
    process.exitCode = 1;
    return;
  }

  const config = loadConfig();

  const developmentLogPath = writeDraft(
    path.join(REPO_ROOT, config.output_folders.development_log),
    handoff.milestone_id,
    generateDevelopmentLog(handoff, config, handoffPath)
  );

  const linkedinPath = writeDraft(
    path.join(REPO_ROOT, config.output_folders.linkedin),
    handoff.milestone_id,
    generateLinkedIn(handoff, config, handoffPath)
  );

  const releaseNotesPath = writeDraft(
    path.join(REPO_ROOT, config.output_folders.release_notes),
    handoff.milestone_id,
    generateReleaseNotes(handoff, config, handoffPath)
  );

  process.stdout.write("Generated drafts (review before publishing):\n");
  process.stdout.write(`  ${path.relative(REPO_ROOT, developmentLogPath)}\n`);
  process.stdout.write(`  ${path.relative(REPO_ROOT, linkedinPath)}\n`);
  process.stdout.write(`  ${path.relative(REPO_ROOT, releaseNotesPath)}\n`);
}

main();
